apiVersion: v1
kind: Pod
metadata:
  name: runasnonroot-dev
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:1.25

      securityContext:
        allowPrivilegeEscalation: false

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"