apiVersion: v1
kind: Pod
metadata:
  name: dev-privileged-deny
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"