{
 "title": "Webhook Final",
 "time": { "from": "2026-06-23T00:42:20.045Z", "to": "2026-06-24T00:42:20.045Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "description": "Toplam gelen istek",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(admission_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Allowed Request",
   "type": "stat",
   "description": "Toplam izin verilen istekler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(admission_requests_allowed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Denied Request",
   "type": "stat",
   "description": "Reddedilen istekler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(admission_requests_denied_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Based Deny Counts",
   "type": "bargauge",
   "description": "Her policy için kaç deny verilmiş",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"admission_deny_(privileged|root_user|privilege_escalation|non_root|latest_image|hostpath|disallowed_storage_class|pvc_lookup_failed)_total\"})",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sum(admission_deny_missing_requests_cpu_total)\r\n+\r\nsum(admission_deny_missing_requests_memory_total)\r\n+\r\nsum(admission_deny_missing_limits_cpu_total)\r\n+\r\nsum(admission_deny_missing_limits_memory_total)",
     "legendFormat": "Missing Resources"
    }
   ]
  },
  {
   "title": "Admission Request Rate",
   "type": "timeseries",
   "description": "Son 5 dakikadaki admission request yoğunluğunu gösterir.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(admission_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Policy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(admission_deny_hostpath_total)",
     "legendFormat": "HostPath Volume"
    },
    {
     "expr": "sum(admission_deny_disallowed_storage_class_total)",
     "legendFormat": "Disallowed StorageClass"
    },
    {
     "expr": "sum(admission_deny_pvc_lookup_failed_total)",
     "legendFormat": "PVC Lookup Failed"
    }
   ]
  },
  {
   "title": "Resource Policy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(admission_deny_missing_requests_cpu_total)",
     "legendFormat": "Missing CPU Request"
    },
    {
     "expr": "sum(admission_deny_missing_requests_memory_total)",
     "legendFormat": "Missing Memory Request"
    },
    {
     "expr": "sum(admission_deny_missing_limits_cpu_total)",
     "legendFormat": "Missing CPU Limit"
    },
    {
     "expr": "sum(admission_deny_missing_limits_memory_total)",
     "legendFormat": "Missing Memory Limit"
    }
   ]
  },
  {
   "title": "Security Policy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(admission_deny_privileged_total)",
     "legendFormat": "Privileged Container"
    },
    {
     "expr": "sum(admission_deny_root_user_total)",
     "legendFormat": "Root User"
    },
    {
     "expr": "sum(admission_deny_privilege_escalation_total)",
     "legendFormat": "Privilege Escalation"
    },
    {
     "expr": "sum(admission_deny_non_root_total)",
     "legendFormat": "RunAsNonRoot Missing"
    }
   ]
  },
  {
   "title": "Image",
   "type": "gauge",
   "description": "Latest image sayısı",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(admission_deny_latest_image_total)",
     "legendFormat": "Latest or Tagless Image"
    }
   ]
  }
 ]
}