apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-security-webhook
webhooks:
- name: podsecurity.webhook.example.com
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      name: pod-security-webhook
      namespace: webhook-system
      path: /validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lVRVc2ajRNN1dnQWtoeHVicUpSQWI4UllzVWhRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF3d1hjRzlrTFhObFkzVnlhWFI1TFhkbFltaHZiMnN0WTJFd0hoY05Nall3TlRFMQpNVEV5TURVeFdoY05Nell3TlRFeU1URXlNRFV4V2pBaU1TQXdIZ1lEVlFRRERCZHdiMlF0YzJWamRYSnBkSGt0CmQyVmlhRzl2YXkxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1mOGVuME8KU3JyYjVrMXBmZ3JXT3VQWGVxUU9qbWx6bm45RzhHV3lsRE81TlpuTnZ3RDdOcTNiR1daMkYvODl3bCtIUEQrRgp5NkM4UXprTzM5a0NKNTQyOGFFckZiYm5WQUdKZW5JZmFIZmNoNzNUUndIV0pRNkpJaDdtUTRZVzUwUmErdXZXCkdYTjZBVFZTWTlmQ2c3R0s5ajd1U0VNT0l6RnZRdmhIV2sxcW1sbGVpYytTcElOd1QxMlNVM2JxenZpdnVERm8KajRkbmZYOHlpYVQzWVBsa1I1ak9sN3BvczR1Sm5hYW82RHFYZjhzS093NHIyRWNqWXY3OWdFblZQc1U2MU90QQpURjlMalR0ZjJPWGl5QXkxRmlqdjkvZW1PaG9VU2tyNm1YcjVPTXpuNmp3SHNPd3lURWREUUJXandjc0FDV0FzCjJZeEZzSEpWZmFkVWYxMENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGQUdJSWFoUTFwSnUxaDhMT2lTZ05uakwKTThVL01COEdBMVVkSXdRWU1CYUFGQUdJSWFoUTFwSnUxaDhMT2lTZ05uakxNOFUvTUE4R0ExVWRFd0VCL3dRRgpNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFN0JqRC9OZ1hGZkRhc3kzb0daK09QbGF5M2NxcmNyCmdwWnI3eGtmK2VoVW16ckV4bVBxM0I0Y2NDbTZqQkcvNlRrY0x0cDFyRG9tdzkzcmpqMEFOOUNYcFN5T2w5VTcKTy9STlhNSUdMcmhBcW5tTS8yZWxvdVl1a01UV2NteE8ybVRWejQwb2hxODloVzY2Sk1UbFlwSFR2S3ZOQnlkSApJejVBd3NaWXBZbzNtL1FNdUYrOTdEcVl1S2ZKZUt6amJxSWhzRGUwR3BpMnNieWdXQ212ZjJLa29iSk5FdkR3CmpVZHArYkVBa0pQVEFSZ28wREIxdWRjeWZmZGhnS1EzZUltTnZIWFAwcjZ1SHlCcUxXM2NLNU16MmVCUCtOTnEKMGE2RGlxVlF3aUZZblNEcHFqa3NIaXVqbTRPMHc1dnRaU3BTb29NZytwQUlrODNSdWZuc2U0RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]

  namespaceSelector:
    matchLabels:
      webhook: enabled

  objectSelector:
    matchExpressions:
    - key: app
      operator: NotIn
      values:
      - pod-security-webhook