apiVersion: v1
kind: Pod
metadata:
  name: root-user-test
  namespace: test
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]

      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: false

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"