apiVersion: v1
kind: Pod
metadata:
  name: latest-image-default
  namespace: default
spec:
  securityContext:
    runAsNonRoot: true

  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:latest

      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"